### ISSUE TITLE
Login information reset after each launch/restart

### ISSUE THREAD

**Issue by TheMiziko** [Zero-to-Heroes/hdt-plugin-zerotoheroes#18]
Hello ! So, I had this issue not only with zth plugin, but with HDT in general, it sometimes resets information about my plugins(if they are enabled/disabled, some settings, etc)
In this case, it resets my login information, despite them being in files. So there should be any issues. Perhaps it reads information from txt files incorrectly.
Here's my log :

[log_2492016-20714.txt](https://github.com/Zero-to-Heroes/hdt-plugin-zerotoheroes/files/491261/log_2492016-20714.txt)

**Comment by sebastientromp** [comment]
Hey! I noticed this after the last update - the plugins were disabled, and login info was reset. On my side it was working properly after subsequent resets though.

The logs show an error when connecting to the ZetoH site (something I'll track and handle through #9), but nothing linked to reading the login information and settings.
I'll keep an eye on this and will see if it happens again (after an update, or independently from one).

Thanks for the report!

**Comment by sebastientromp** [comment]
Looks like this is a generic HDT issue (nothing I can do on my side), don't hesitate to +1 it on their side: https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2849
