### ISSUE TITLE
Incompatibility with "Treasury"plugin

### ISSUE THREAD

**Issue by TheMiziko** [Zero-to-Heroes/hdt-plugin-zerotoheroes#7]
Hello ! Unfortunetly, it seems like the plugin is not compatible with "tresury
  "plugin from official plugins site :) and It causes treasury to crash when trying to open window
Here are the logs :
[hdt_log_1473746183.txt](https://github.com/Zero-to-Heroes/hdt-plugin-zerotoheroes/files/468980/hdt_log_1473746183.txt)

**Comment by sebastientromp** [comment]
Thanks for reporting this!

Just had a look at the logs, and nothing seems out of the ordinary. Will try to reproduce this myself.

**Comment by sebastientromp** [comment]
Issue reproduced, looking at it

**Comment by sebastientromp** [comment]
Should be fixed in latest release: https://github.com/Zero-to-Heroes/hdt-plugin-zerotoheroes/releases/latest
